/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for Alpine package objects
 */
export type AlpinePackageSchema = AlpineV001Schema;

/**
 * Schema for Alpine Package entries
 */
export interface AlpineV001Schema {
	/**
	 * The public key that can verify the package signature
	 */
	publicKey: {
		/**
		 * Specifies the content of the public key inline within the document
		 */
		content: string;
	};
	/**
	 * Information about the package associated with the entry
	 */
	package: {
		[k: string]: unknown;
	};
}
