/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * COSE for Rekord objects
 */
export type COSESchema = CoseV001Schema;

/**
 * Schema for cose object
 */
export interface CoseV001Schema {
	/**
	 * The COSE Sign1 Message
	 */
	message?: string;
	/**
	 * The public key that can verify the signature
	 */
	publicKey: string;
	/**
	 * Information about the content associated with the entry
	 */
	data: {
		/**
		 * Specifies the hash algorithm and value for the content
		 */
		payloadHash?: {
			/**
			 * The hashing function used to compute the hash value
			 */
			algorithm: "sha256";
			/**
			 * The hash value for the content
			 */
			value: string;
		};
		/**
		 * Specifies the hash algorithm and value for the COSE envelope
		 */
		envelopeHash?: {
			/**
			 * The hashing function used to compute the hash value
			 */
			algorithm: "sha256";
			/**
			 * The hash value for the envelope
			 */
			value: string;
		};
		/**
		 * Specifies the additional authenticated data required to verify the signature
		 */
		aad?: string;
	};
}
