/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for JAR objects
 */
export type JARSchema = JARV001Schema;

/**
 * Schema for JAR entries
 */
export interface JARV001Schema {
	/**
	 * Information about the included signature in the JAR file
	 */
	signature?: {
		/**
		 * Specifies the PKCS7 signature embedded within the JAR file
		 */
		content: string;
		/**
		 * The X509 certificate containing the public key JAR which verifies the signature of the JAR
		 */
		publicKey: {
			/**
			 * Specifies the content of the X509 certificate containing the public key used to verify the signature
			 */
			content: string;
		};
	};
	/**
	 * Information about the archive associated with the entry
	 */
	archive: {
		[k: string]: unknown;
	};
}
