/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for RFC 3161 timestamp objects
 */
export type TimestampSchema = TimestampV001Schema;

/**
 * Schema for RFC3161 entries
 */
export interface TimestampV001Schema {
	/**
	 * Information about the tsr file associated with the entry
	 */
	tsr: {
		/**
		 * Specifies the tsr file content inline within the document
		 */
		content: string;
	};
}
