/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for RPM objects
 */
export type RPMSchema = RPMV001Schema;

/**
 * Schema for RPM entries
 */
export interface RPMV001Schema {
	/**
	 * The PGP public key that can verify the RPM signature
	 */
	publicKey: {
		/**
		 * Specifies the content of the public key inline within the document
		 */
		content: string;
	};
	/**
	 * Information about the package associated with the entry
	 */
	package: {
		[k: string]: unknown;
	};
}
