/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for TUF metadata objects
 */
export type TUFSchema = TUFV001Schema;

/**
 * Schema for TUF metadata entries
 */
export interface TUFV001Schema {
	/**
	 * TUF specification version
	 */
	spec_version?: string;
	/**
	 * TUF metadata
	 */
	metadata: {
		/**
		 * Specifies the metadata inline within the document
		 */
		content: {
			[k: string]: unknown;
		};
	};
	/**
	 * root metadata containing about the public keys used to sign the manifest
	 */
	root: {
		/**
		 * Specifies the metadata inline within the document
		 */
		content: {
			[k: string]: unknown;
		};
	};
}
