#!/usr/bin/env bash

# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

set -o errexit
set -o nounset
set -o pipefail

# Relocate to the root so that this script can be run from anywhere
cd "$(dirname "$0")"/..

if [[ $# -eq 0 ]] ; then
    echo 'Missing rekor version. Example usage: "./hack/update_codegen.sh v1.0.1"'
    exit 0
fi
readonly REF="${1}"

generate_types() {
	TMP_DIR=$(mktemp -d -t ci-XXXXXXXXXX)

	git clone https://github.com/sigstore/rekor.git ${TMP_DIR}
	pushd ${TMP_DIR}
	git checkout ${REF}
	popd

	rm -rf src/
	pnpm exec openapi --input "${TMP_DIR}/openapi.yaml" --output "src" --useOptions --useUnionTypes --name "RekorClient"
	# Default the backend to using TLS
	sed -i "" "s/http:/https:/" "src/core/OpenAPI.ts"
	sed -i "" "s/http:/https:/" "src/RekorClient.ts"

	# Cancel out the `Error` type generated by the API. It's being generated since the Rekor openapi object
	# defaults to the `responses/InternalServerError` type. In reality, errors will be thrown by this API.
	# Cancelling the `Error` type allows clients to not always check the response type.
	mv "src/models/Error.ts" "src/models/RekorError.ts"
	sed -i "" "s/ Error / RekorError /" "src/models/RekorError.ts"
	echo "
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type Error = never;
" > "src/models/Error.ts"
	echo -e '\nexport * from "./models/RekorError";\n' >> "src/index.ts"


	# Run json2ts on schemas
	# Heavily inspired from: https://github.com/sigstore/sigstore-js/blob/main/hack/generate-rekor-types
	KINDS=(
		"alpine"
		"cose"
		"hashedrekord"
		"helm"
		"intoto"
		"jar"
		"rfc3161"
		"rpm"
		"tuf"
	)
	for KIND in "${KINDS[@]}"
	do
		# Override the type generated by `openapi-typescript-codegen`
		TYPE_PATH="${TMP_DIR}/pkg/types/${KIND}"
		pnpm exec json2ts --input "${TYPE_PATH}/${KIND}_schema.json" \
			--cwd "${TYPE_PATH}" \
			--output "src/models/${KIND}.ts" \
			--no-additionalProperties

		# Update the export from `openapi-typescript-codegen`
		sed -i "" "s/.*\.\/models\/${KIND}.*/export \* from '\.\/models\/${KIND}';/" "src/index.ts"
	done

	pnpm exec prettier "src" --write

	rm -rf "${TMP_DIR}"
}

generate_types
